export const CartData = [
  { userID: 1, productID: 1 },
  { userID: 2, productID: 2 },
  { userID: 3, productID: 3 },
  { userID: 4, productID: 4 },
  { userID: 5, productID: 5 },
  { userID: 6, productID: 6 },
  { userID: 7, productID: 7 },
  { userID: 8, productID: 8 },
  { userID: 9, productID: 9 },
  //   { userID: 10, productID: 4 },
  //   { userID: 11, productID:7 },
  //   { userID: 12, productID: 3 },
  //   { userID: 13, productID: 8 },
  //   { userID: 14, productID: 5 },
  //   { userID: 15, productID: 4 },
  //   { userID: 16, productID: 5 },
  //   { userID: 17, productID: 7},
  //   { userID: 18, productID: 7 },
  //   { userID: 19, productID: 6 },
  //   { userID: 20, productID: 5 },
  //   { userID: 21, productID: 4 },
];
