const productsData = [
  {
    title: "Handbag",
    subTitle: "Fashionable handbag",
    description: "High-quality handbag made of leather.",
    price: 50.99,
    quantity: 100,
    discount: 0.1,
    arrival: "2024-04-05",
    brandID: 1,
    categoryID: 1,
  },
  {
    title: "Makeup Set",
    subTitle: "Complete makeup kit",
    description: "A comprehensive makeup set for all occasions.",
    price: 39.99,
    quantity: 50,
    discount: 0,
    arrival: "2024-04-10",
    brandID: 2,
    categoryID: 2,
  },
  {
    title: "Backpack",
    subTitle: "Durable backpack",
    description: "Spacious backpack suitable for everyday use.",
    price: 29.99,
    quantity: 80,
    discount: 0.05,
    arrival: "2024-04-08",
    brandID: 3,
    categoryID: 1,
  },
  {
    title: "Lipstick Set",
    subTitle: "Assorted lipstick pack",
    description: "Set of 6 long-lasting lipstick shades.",
    price: 19.99,
    quantity: 60,
    discount: 0.15,
    arrival: "2024-04-12",
    brandID: 2,
    categoryID: 2,
  },
  {
    title: "Wallet",
    subTitle: "Classic leather wallet",
    description: "Elegant wallet with multiple compartments.",
    price: 25.5,
    quantity: 120,
    discount: 0.1,
    arrival: "2024-04-06",
    brandID: 1,
    categoryID: 3,
  },
  {
    title: "Foundation",
    subTitle: "Matte finish foundation",
    description: "Oil-free foundation for a natural look.",
    price: 115.99,
    quantity: 70,
    discount: 0.05,
    arrival: "2024-04-15",
    brandID: 5,
    categoryID: 2,
  },
  {
    title: "Sunglasses",
    subTitle: "Stylish sunglasses",
    description: "UV-protective sunglasses with polarized lenses.",
    price: 135.75,
    quantity: 90,
    discount: 0.2,
    arrival: "2023-04-09",
    brandID: 4,
    categoryID: 1,
  },
  {
    title: "Eyeliner",
    subTitle: "Waterproof eyeliner pen",
    description: "Long-lasting eyeliner for precise application.",
    price: 9.99,
    quantity: 100,
    discount: 0,
    arrival: "2023-04-14",
    brandID: 4,
    categoryID: 2,
  },
  {
    title: "Shoulder Bag",
    subTitle: "Versatile shoulder bag",
    description: "Compact bag with adjustable strap.",
    price: 19.5,
    quantity: 80,
    discount: 0.15,
    arrival: "2023-04-07",
    brandID: 1,
    categoryID: 1,
  },
  {
    title: "Mascara",
    subTitle: "Volumizing mascara",
    description: "Lengthening and volumizing mascara for fuller lashes.",
    price: 12.99,
    quantity: 60,
    discount: 0.35,
    arrival: "2023-04-13",
    brandID: 2,
    categoryID: 4,
  },
  {
    title: "Mascara-2",
    subTitle: "Volumizing mascara",
    description: "Lengthening and volumizing mascara for fuller lashes.",
    price: 12.99,
    quantity: 60,
    discount: 0.25,
    arrival: "2023-04-13",
    brandID: 2,
    categoryID: 4,
  },
  {
    title: "Mascara-3",
    subTitle: "Volumizing mascara",
    description: "Lengthening and volumizing mascara for fuller lashes.",
    price: 12.99,
    quantity: 60,
    discount: 0.15,
    arrival: "2023-04-13",
    brandID: 2,
    categoryID: 4,
  },
  {
    title: "Shoulder Bag-1",
    subTitle: "Versatile shoulder bag",
    description: "Compact bag with adjustable strap.",
    price: 19.5,
    quantity: 80,
    discount: 0.16,
    arrival: "2023-04-07",
    brandID: 1,
    categoryID: 1,
  },
  {
    title: "Shoulder Bag-2",
    subTitle: "Versatile shoulder bag",
    description: "Compact bag with adjustable strap.",
    price: 19.5,
    quantity: 80,
    discount: 0.1,
    arrival: "2023-04-07",
    brandID: 1,
    categoryID: 1,
  },
  {
    title: "Shoulder Bag-3",
    subTitle: "Versatile shoulder bag",
    description: "Compact bag with adjustable strap.",
    price: 19.5,
    quantity: 80,
    discount: 0.1,
    arrival: "2023-04-07",
    brandID: 1,
    categoryID: 1,
  },
  {
    title: "Eyeliner-1",
    subTitle: "Waterproof eyeliner pen",
    description: "Long-lasting eyeliner for precise application.",
    price: 9.99,
    quantity: 100,
    discount: 0,
    arrival: "2023-04-14",
    brandID: 4,
    categoryID: 2,
  },
];

export { productsData };
