export const userData = [
  {
    firstName: "Griswold",
    lastName: "Tettersell",
    email: "gtettersell0@sciencedaily.com",
    password: "$10$v2Bgadow5FfTJ79iUM6wsOSZ49chrvUokwOkUv6KBwEL0ccmKOMTu",
    phoneNumber: "810-528-0390",
    image: "https://robohash.org/possimusveniamtempora.png?size=50x50&set=set1",
    dateOfBirth: "8/13/2023",
  },
  {
    firstName: "Dione",
    lastName: "Platfoot",
    email: "dplatfoot1@reverbnation.com",
    password: 'qycaLCFT3111%?,"',
    phoneNumber: "637-835-8545",
    image: "https://robohash.org/enimcumquedolores.png?size=50x50&set=set1",
    dateOfBirth: "8/24/2023",
  },
  {
    firstName: "Gerda",
    lastName: "Tenny",
    email: "gtenny2@salon.com",
    password: "erTY58&*",
    phoneNumber: "187-945-9811",
    image: "https://robohash.org/quiinconsequatur.png?size=50x50&set=set1",
    dateOfBirth: "1/2/2024",
  },
  {
    firstName: "Hercules",
    lastName: "Le Monnier",
    email: "hlemonnier3@homestead.com",
    password: "tolhLVVY7019",
    phoneNumber: "885-277-0592",
    image: "https://robohash.org/explicaboquaequi.png?size=50x50&set=set1",
    dateOfBirth: "12/8/2023",
  },
  {
    firstName: "Zerk",
    lastName: "Neeson",
    email: "zneeson4@dailymail.co.uk",
    password: "vgfkDHAQ3720{>~@zeuWMe)$n",
    phoneNumber: "219-602-7166",
    image: "https://robohash.org/abatet.png?size=50x50&set=set1",
    dateOfBirth: "10/8/2023",
  },
  {
    firstName: "Nessy",
    lastName: "Fabbri",
    email: "nfabbri5@census.gov",
    password: "mxjeXUAR2764`}\\?xL",
    phoneNumber: "424-230-6956",
    image:
      "https://robohash.org/quasinesciuntconsequatur.png?size=50x50&set=set1",
    dateOfBirth: "2/24/2024",
  },
  {
    firstName: "Willabella",
    lastName: "Cornewell",
    email: "wcornewell6@tinypic.com",
    password: 'dpedIKQK0327=_#.pY"YwT}zo',
    phoneNumber: "686-422-6508",
    image: "https://robohash.org/vitaenisiaut.png?size=50x50&set=set1",
    dateOfBirth: "8/20/2023",
  },
  {
    firstName: "Denys",
    lastName: "Bence",
    email: "dbence7@symantec.com",
    password: "pnieJALF6908#`.@4.7",
    phoneNumber: "134-769-5160",
    image: "https://robohash.org/excepturiimpeditamet.png?size=50x50&set=set1",
    dateOfBirth: "2/4/2024",
  },
  {
    firstName: "Axel",
    lastName: "Emett",
    email: "aemett8@diigo.com",
    password: "ffnzFXYE8529%!_@JD.E1NTaOCgZk|9",
    phoneNumber: "926-779-6273",
    image: "https://robohash.org/quiaiustovelit.png?size=50x50&set=set1",
    dateOfBirth: "6/11/2023",
  },
  {
    firstName: "Der",
    lastName: "Wonfar",
    email: "dwonfar9@thetimes.co.uk",
    password: 'hoxeMMFL9013/(\\`R"<6G',
    phoneNumber: "468-563-1054",
    image: "https://robohash.org/etnihilarchitecto.png?size=50x50&set=set1",
    dateOfBirth: "9/24/2023",
  },
];
